app/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, TextField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import User
from flask_login import current_user


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    category = SelectField('Categories', choices=[('Product Pitch', 'Product Pitch'), ('Sales', 'Sales Pitch'), ('Business Pitch', 'Business Pitch'), ('Interview Pitch', 'Interview Pitch')], validators=[DataRequired()])
    submit = SubmitField('Post')
    
    
class CommentForm(FlaskForm):
    comment = TextAreaField('Comment')
    submit = SubmitField('Submit')

app/posts/views.py
from flask import (render_template, url_for, flash,redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from app import db
from app.models import Post, User, Comment
from app.posts.forms import PostForm, CommentForm

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user, category=form.category.data)
        db.session.add(post)
        db.session.commit()
        flash('You pitch has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('new-post.html', title='New Pitch', form=form, legend='New Pitch')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id = post_id).all()
    return render_template('post.html', title=post.title, post=post, comments = comments)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your pitch has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('new-post.html', title='Update Post', form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your pitch has been deleted!', 'success')
    return redirect(url_for('main.home'))  

@posts.route("/post/<string:category>")
def category_post(category):
    
    post = Post.query.filter_by(category=category).all()
    print("..............", post)
    return render_template('category.html', post=post, category=category) 

@posts.route("/post/<int:post_id>/comment", methods=['GET', 'POST'])
@login_required
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(comment=form.comment.data, author=current_user, post_id = post_id )
        db.session.add(comment)
        db.session.commit()
        # comments = Comment.query.all()
        flash('You comment has been created!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    return render_template('new-content.html', title='New Comment', form=form, legend='New Comment')

app/users/views.py
import os
from .. import mail
from flask import render_template, url_for, flash, redirect, request, Blueprint, url_for, current_app
from flask_login import login_user, current_user, logout_user, login_required
# from app import db, bcrypt
from app.models import User, Post, Comment
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
# import secrets
from PIL import Image
from flask_mail import Message
from ..email import mail_message

users = Blueprint('users', __name__)


# def register():
#     if current_user.is_authenticated:
#         return redirect(url_for('main.home'))
#     form = RegistrationForm()
#     if form.validate_on_submit():
#         hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
#         user = User(username=form.username.data, email=form.email.data, password=hashed_password)
#         db.session.add(user)
#         db.session.commit()
                
#         flash('Your account has been created! You are now able to log in', 'success')
#         # mail_message("Welcome to PitchRank","email/welcome_user",user.email,user=user)

#         return redirect(url_for('users.login'))
#     return render_template('register.html', title='Register', form=form)

@users.route("/register", methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user =  User(email = form.email.data, username = form.username.data, password = form.password.data)
        user.save_user()
        try:
            msg = Message('Hello! Welcome to PITCH. We are glad you joined us.',sender=('nicoleochola@gmail.com'))
            msg.add_recipient(user.email)
            mail.send(msg)
        except Exception as e:
            print('failed')
        return redirect(url_for('users.login'))
        title = "New Account"
    return render_template('register.html', title='Register', form=form)

# def login():
#     if current_user.is_authenticated:
#         return redirect(url_for('main.home'))
#     form = LoginForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         if user and bcrypt.check_password_hash(user.password, form.password.data):
#             login_user(user, remember=form.remember.data)
#             next_page = request.args.get('next')
#             return redirect(next_page) if next_page else redirect(url_for('main.home'))
#         else:
#             flash('Login Unsuccessful. Please check email and password', 'danger')
#     return render_template('login.html', title='Login', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    # import pdb; pdb.set_trace()
    if login_form.validate_on_submit():
        user = User.query.filter_by(email = login_form.email.data).first()
        # import pdb; pdb.set_trace()
        if user is not None and user.verify_password(login_form.password.data):
            login_user(user,login_form.remember.data)
            return redirect(request.args.get('next') or url_for('main.home'))
        else:
            flash('Invalid Username or Password')
    return render_template('login.html',form = login_form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


def save_picture(form_picture):
    randome_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_picture.filename)
    picture_name = randome_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/profile_pics', picture_name)
    
    output_size = (125, 125)
    final_image = Image.open(form_picture)
    final_image.thumbnail(output_size)
    
    final_image.save(picture_path)
    
    return picture_name

@users.route("/account",  methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image = picture_file
            
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated.', 'success')
        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=current_user.username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.posted_date.desc()).all()
    print('--------', posts)
    image_file = url_for('static', filename='profile_pics/' + current_user.image)
    return render_template('account.html', title='Account', posts=posts, user=user, image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.posted_date.desc()).paginate(page=page, per_page=10)
    return render_template('userposts.html', posts=posts, user=user)

app/templates/about.html
{% extends "layout.html" %}

{% block content%} 
<div class="mt-5 pt-5">
    <h1>About Pitch App</h1>
    <p>First impressions can make or break you, make it count!</p>

</div>
{% endblock content %}

app/templates/account.html
{% extends "layout.html" %}

{% block content%} 
<div class="content-section pt-4 mt-5 mb-4 pb-4">
    <div class="row">
    <div class="col-md-6">
        <div class="media">
          <img class="rounded-circle account-img" src="https://source.unsplash.com/125x125/?profile,photo">
          <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
          </div>
        </div>
          <form method="POST" action="" enctype="multipart/form-data">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4">Account Information</legend>
                  <div class="form-group">
                      {{ form.username.label(class="form-control-label") }}
  
                      {% if form.username.errors %}
                          {{ form.username(class="form-control form-control-lg is-invalid") }}
                          <div class="invalid-feedback">
                              {% for error in form.username.errors %}
                                  <span>{{ error }}</span>
                              {% endfor %}
                          </div>
                      {% else %}
                          {{ form.username(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.email.label(class="form-control-label") }}
                      {% if form.email.errors %}
                          {{ form.email(class="form-control form-control-lg is-invalid") }}
                          <div class="invalid-feedback">
                              {% for error in form.email.errors %}
                                  <span>{{ error }}</span>
                              {% endfor %}
                          </div>
                      {% else %}
                          {{ form.email(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.picture.label() }}
                      {{ form.picture(class="form-control-file") }}
                      {% if form.picture.errors %}
                          {% for error in form.picture.errors %}
                              <span class="text-danger">{{ error }}</span></br>
                          {% endfor %}
                      {% endif %}
                  </div>
              </fieldset>
              <div class="form-group">
                  {{ form.submit(class="btn btn-outline-info") }}
              </div>
          </form>
        </div>
        <div class="col-md-3 pt-4 mt-4 ml-4">
            <h3 class="text-center">My Pitches</h3>
            
            {% if posts %}
                {% for post in posts %}
                    <ul>
                        <li><p><a class="" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></p>
                        </li>
                    </ul>
                    {% endfor %}
                    {% else %}
                    <p>You have not posted any pitch</p>
                   
                {% endif %}

        </div> 
    </div>
</div>

{% endblock content %}

app/templates/category.html
{% extends "layout.html" %}

{% block content%} 
    <h2 class="mb-4 mt-2 pt-2"> Pitches in {{category}} </h2>

    {% for post in post %}

    <article class="media content-section">
      <img class="rounded-circle article-img" src="https://source.unsplash.com/125x125/?profile,photo" alt="{{ post.author.username }} profile photo">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted mr-2">{{ post.posted_date.strftime('%Y-%m-%d') }}</small>
                <small class="mr-2">Posted in: <a class="mr-2" href="{{ url_for('posts.category_post', category=post.category) }}">{{ post.category }}</a></small>

              </div>
              <h2><a class="article-title mt-2" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content }}</p>
            </div>
            <p class="article-footer"><a class="ratings" href="{{ url_for('posts.new_comment', post_id=post.id) }}"> Leave a comment</a></p>
    </article>
    {% endfor %}
    

{% endblock content %}
       

app/templates/error404.html
{% extends 'layout.html'%}

{% block content %}
<div class="text-center jumbotron mt-5 pt-4">
        <h2 class="mt-4">Oh no! :( we can't find that page</h2>
        <p>Please check to make sure that the URL is correct.</p>

</div>
    
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}

{% block jumbo%}
<div class="jumbotron card card-image" style="background-image: url(https://mdbootstrap.com/img/Photos/Others/gradient1.jpg);">
  <div class="text-white text-center py-5 px-4">
      <div>
        <h2 class="card-title h1-responsive mt-4 font-bold"><strong>Welcome to Pitch App</strong></h2>
        <h4 class="mb-5 text-white">Pitching ideas one minute at a time!</h4>
      </div>
  </div>
</div>
{% endblock %}

{% block content%} 
<h2 class=" font-bold">Latest Pitches</h2>

    {% for post in posts.items %}

    <article class="media content-section">
      <img class="rounded-circle article-img" src="https://source.unsplash.com/125x125/?profile,photo" alt="{{ post.author.username }} profile photo">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                
                <small class="text-muted mr-2">{{ post.posted_date.strftime('%Y-%m-%d') }}</small> 

                <small>Posted in: <a class="mr-2" href="{{ url_for('posts.category_post', category=post.category) }}">{{ post.category }}</a></small>

              </div>
              <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content | truncate(100) }}</p>
              <small><a class="article-readmore" href="{{ url_for('posts.post', post_id=post.id) }}">read more...</a></small>
            </div>
            <p class="article-footer"><a class="ratings" href="{{ url_for('posts.new_comment', post_id=post.id) }}"> Leave a comment</a></p>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
      <a class="btn btn-sm btn-info mb-2 mt-2" href="{{ url_for('main.home', page=page_num) }}"> {{page_num}} </a>
        {% else %}
        <a class="btn btn-sm btn-outline-info mb-2 mt-2" href="{{ url_for('main.home', page=page_num) }}"> {{page_num}} </a>
        {% endif %}

      {% else %}
        ...
      {% endif %}

    {% endfor %}

{% endblock content %}
       

app/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon-16x16.png') }}">
    {% if title %}
    <title> {{title}} - Pitch || App </title>
    {% else %}
    <title>Pitch || App </title>
    {% endif%}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/js/mdb.min.js"></script>


</head>

<body>
    {% block navbar %}

    {% include 'navbar.html' %}

    {% endblock %}

    {% block jumbo%}
    {% endblock %}
    <main role="main" class="container mt-5 pt-2">
        <div class="row">
            <div class="col-md-9">
                {% with messages = get_flashed_messages(with_categories=true) %}

                {% if messages%}

                {% for category, message in messages %}
                <div class="alert alert-{{category}}">
                    {{message}}
                </div>
                {% endfor %}

                {% endif %}

                {% endwith %}

                {% block content %}

                {% endblock content %}
            </div>
            <div class="col-md-3 mt-5 pt-5">
                <div class="content-section">
                    <h3>Pitch Categories</h3>
                    <p class='text-muted'>Filter based on Categories.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light"><a href="/post/Product%20Pitch">Product
                                Pitch</a> </li>
                        <li class="list-group-item list-group-item-light"><a href="/post/Interview%20Pitch">Interview
                                Pitch</a> </li>
                        <li class="list-group-item list-group-item-light"><a href="/post/Sales">Sales Pitch</a> </li>
                        <li class="list-group-item list-group-item-light"><a href="/post/Business%20Pitch">Business
                                Pitch</a> </li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    
    <footer class="page-footer font-small blue-gradient mt-4 pt-4">

        
        <div class="footer-copyright text-center py-3">© 2022 Copyright.
            <a href="https://github.com/amon-wanyonyi/pitch1"> Amon Wanyonyi</a>
        </div>
        

    </footer>
    
</body>

</html>

app/templates/login.html
 
{% extends "layout.html" %}
{% block content %}
    <div class="content-section mt-5 pt-3 mb-4">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

app/templates/navbar.html
<!-- <header class="site-header"> -->
  <nav class="navbar navbar-expand-lg navbar-dark blue-gradient fixed-top">
    <div class="container">
    <a class="navbar-brand mr-4" href="/">Pitch App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
        <a class="nav-item active nav-link" href="/">Home</a>
        <a class="nav-item nav-link" href="/about">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
        {% if current_user.is_authenticated %}
        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Pitch</a>
        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">My Account</a>
        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
        {% else %}
        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
        {% endif %}
        </div>
    </div>
    </div>
    </nav>
    <!-- </header> -->

app/templates/new-content.html
{% extends "layout.html" %}

{% block content%} 
<div class="content-section mt-4 pt-4">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
            
                <div class="form-group">
                    {{ form.comment.label(class="form-control-label") }}
                    {% if form.comment.errors %}
                        {{ form.comment(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.comment.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.comment(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock content %}

app/templates/post.html
{% extends "layout.html" %}

{% block content%} 

    <article class="media content-section mt-5 pt-2">
      <img class="rounded-circle article-img" src="https://source.unsplash.com/125x125/?profile,photo" alt="{{ post.author.username }} profile photo">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted mr-2">{{ post.posted_date.strftime('%Y-%m-%d') }}</small>
                <small>Posted in: <a class="mr-2" href="{{ url_for('posts.category_post', category=post.category) }}">{{ post.category }}</a></small>

                {% if post.author == current_user%}
                <div>
                    <a class="btn btn-secondary btn-sm mt-2 mb-2" href="{{ url_for('posts.update_post', post_id=post.id) }}">Edit</a>
                    <button type="button" class="btn btn-danger btn-sm m-1 mb-1"  data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>

                {% endif %}
              </div>
              <h2 class="article-title mt-2">{{ post.title }}</h2>
              <p class="article-content">{{ post.content }}</p>
            </div>
    </article>
    <div class="content-section">
        <a class="ratings" href="{{ url_for('posts.new_comment', post_id=post.id) }}"> Write a comment</a>

        <div class="mt-4 mb-4">

                <h2>Comments</h2>
                <hr>
                {% if comments %}
                {% for comment in comments %}

                <ul>
                    <small>Posted by: {{comment.post.author.username}}</small></li>
                    <li><h4> {{ comment.comment }} </h4>
                </ul>
            
            {% endfor %} 
            {% else %}
                <p>No comments</p>
            {% endif %}
            </div>
    </div>
   <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
        </div>

{% endblock content %}
       

app/templates/userposts.html
{% extends "layout.html" %}

{% block content%} 
    <h2 class="mb-4 mt-5 pt-4"> {{ posts.total }} Pitches by {{user.username}} </h2>

    {% for post in posts.items %}

    <article class="media content-section">
      <img class="rounded-circle article-img" src="https://source.unsplash.com/125x125/?profile,photo" alt="{{ post.author.username }} profile photo">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted mr-2">{{ post.posted_date.strftime('%Y-%m-%d') }}</small>
                <small>Posted in: <a class="mr-2" href="{{ url_for('posts.category_post', category=post.category) }}">{{ post.category }}</a></small>

              </div>
              <h2><a class="article-title mt-2" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content }}</p>
            </div>
            <p class="article-footer"><a class="ratings" href="{{ url_for('posts.new_comment', post_id=post.id) }}"> Leave a comment</a></p>


    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
      <a class="btn btn-sm btn-info mb-2 mt-2" href="{{ url_for('users.user_posts', username = user.username, page=page_num) }}"> {{page_num}} </a>
        {% else %}
        <a class="btn btn-sm btn-outline-info mb-2 mt-2" href="{{ url_for('users.user_posts', username = user.username, page=page_num) }}"> {{page_num}} </a>
        {% endif %}

      {% else %}
        ...
      {% endif %}

    {% endfor %}

{% endblock content %}
       